### ISSUE TITLE
Page snippets not being rendered after updating page.

### ISSUE THREAD

**Issue by vannut** [rainlab/pages-plugin#326]
I somehow have a strange issue going on on my production machine; and I can't figure out how this is possible. 

I've got a static page with besides some text on it also some page-snippets. When changing the text via the backend, hitting save and goin to the front-end to see the cahnges: the page snippets are not being rendered anymore. They show the <figure...> tags instead of the rendered underlying page snippets.

![schermafbeelding 2018-02-05 om 15 18 18](https://user-images.githubusercontent.com/7419859/35809270-6b22b37e-0a88-11e8-9ce9-d5d809117b29.png)

When visiting the page in a 'private' window; or a different browser; the page snippets are rendered correctly; switching back to the old browser window and refreshing, now also shows the rendered age snippets. 

Anybody knows a reason why these snippets are not being rendered?

**Comment by LukeTowers** [comment]
Does it have anything to do with the recent fixes to the caching key to properly support multilanguage?

**Comment by vannut** [comment]
It might be; but running `php artisan cache:clear` should fix that; but in fact it doesn't fix it.

**Comment by host138** [comment]
@LukeTowers same problem, but `php artisan cache:clear` fix for me.
When do you plan to fix it?

**Comment by LukeTowers** [comment]
When do you @host138? I'm not going to do anything about it for free because it's not affecting me. Are you able to read the code and figure out why the cache isn't getting properly cleared on saving of the page?

**Comment by kakajansh** [comment]
I had similar issue, for me issue appears when `CACHE_DRIVER` type is `file`, when I change it to any other type it works

**Comment by mauserrifle** [comment]
I found the issue! Details and hofix here: https://github.com/rainlab/translate-plugin/pull/471

**Comment by bennothommo** [comment]
@mauserrifle Could you please confirm if this issue still exists in the latest version of October CMS (build 452) and with the latest versions of the Pages and Translate plugins?

**Comment by mauserrifle** [comment]
I will check next week. Are there changes to the cache clearing then (clearing all languages instead of 1 now)? Because the lack of that is causing it.

**Comment by bennothommo** [comment]
@mauserrifle Thanks heaps. There's been some extensive work done to the Translate plugin recently so it may be possible it has been resolved. If the issue is still occurring, we'll take another look at it.

**Comment by mauserrifle** [comment]
@bennothommo Nope still not fixed. So: 

`RainLab\Pages\Classes\Snippet::clearMapCache` clears one cache key (main language, all others not). You can test this by adding `dump(self::getMapCacheKey($theme))` inside `clearMapCache`. Just one dump happens. In my case `2403172130snippet-map-nl`. It is skipping `-en` etc. 

The solution should be fairly easy but I think requires updating both plugins due to the events only understanding one cache key (e.g. `pages.snippet.getMapCacheKey`).

**Comment by bennothommo** [comment]
@mauserrifle Thanks for letting us know.

**Comment by mauserrifle** [comment]
@bennothommo Not sure I will have the time. But I will keep in mind. Would you prefer the cache key event (such as `pages.snippet.getMapCacheKey` to be a mixed value `string|array` or a new event such as `pages.snippet.getMapCacheKeys` (plural)?

**Comment by bennothommo** [comment]
@mauserrifle To be honest, I'm still going through the entire capabilities of the Translate plugin (only made a member of the org a couple of days ago and it's not a plugin I use often), so I'm not entirely sure what is the best course of action is.

I would imagine that whichever function is clearing the cache for the main language, it would be a case of querying all available languages and just changing the language marker in the cache key to match the languages, as they would all share a common key name. But it's likely a lot more involved than that.

**Comment by LukeTowers** [comment]
The cache key is generated based on the currently active locale, that was implemented for a reason, so any solution that changes that needs to take the original problem into consideration. It should be linked in the history of the code changes.

**Comment by bennothommo** [comment]
@w20k @mjauvin May I be able to get some testing assistance on this, and confirm if the bug still exists?

**Comment by MaTToX3** [comment]
Issue still exists in Pages v1.2.21 and Translate v1.6.0.

**Comment by w20k** [comment]
@bennothommo look at it today, maybe I even know where the issue is!

**Comment by geez0x1** [comment]
I would just like to raise that I was able to reproduce this issue today :) So it still exists. I can also confirm that `php artisan cache:clear` fixes it consistently (albeit temporarily until the next page rewrite).

**Comment by mjauvin** [comment]
Shouldn't that be resolved by https://github.com/rainlab/translate-plugin/pull/496 ?

@geez0x1 Can you confirm what versions of the plugins you are using?

**Comment by geez0x1** [comment]
@mjauvin The affected site is running build 467, Translate 1.6.7, and Pages 1.3.3. That pull request seems to be talking about menu's, which this is not about?

**Comment by mjauvin** [comment]
@geez0x1 It's doing two things:

                        \RainLab\Pages\Classes\Page::clearMenuCache($theme);
                        \RainLab\Pages\Classes\SnippetManager::clearCache($theme);

When handling the `pages.object.save` event ... this is VERY similar to a suggested fix higher in this thread.

**Comment by geez0x1** [comment]
It seems I have to upgrade to PHP 7.4 before being able to update (things break tremendously), but I'll try it and come back here :+1:

**Comment by geez0x1** [comment]
Alright I've updated to the latest versions after some hassle moving to docker as well; but the issue persists with build 468, Translate 1.6.7, and Pages 1.3.5. Could it be that fix is not available yet given that I see the pull request is associated to milestone 1.6.9 for the Translate plugin?

**Comment by mjauvin** [comment]
You'd need to set `edgeUpdate => true` in `config/cms.php`

**Comment by geez0x1** [comment]
After setting that and upgrading the Translate plugin to 1.7.2 (no other updates), I can confirm the bug still persists. I still see `<figure>` tags and `php artisan cache:clear` fixes it temporarily.

**Comment by mjauvin** [comment]
@LukeTowers any idea why this is still happening?

**Comment by LukeTowers** [comment]
@mjauvin nope. Are you able to replicate it?

**Comment by geez0x1** [comment]
If there's anything else that I could test, let me know. Doing a cache clear is workable for me, but not for my users I'm afraid.

**Comment by LukeTowers** [comment]
@geez0x1 the next step I would recommend is to switch to using the develop branch / L6 update: https://github.com/octoberrain/meta/blob/master/l6-upgrade-notes.md#testing-instructions

**Comment by geez0x1** [comment]
@LukeTowers Thanks for the suggestion! I'm busy for a number of days, but I'll try to test that soon and report back here.

**Comment by geez0x1** [comment]
@LukeTowers Sorry it took me a while to get back here, haven't had time. Anyway; I'm running in a php:apache docker container, where I somehow can't install composer from apt. Is that the only way of trying this?

**Comment by LukeTowers** [comment]
the order of the data attributes shouldn't matter AFAIK

**Comment by geez0x1** [comment]
So I assume it is then recognizing the page and drawing on the cache?

Also, is composer the only way of trying the new code? See my earier comment about docker containers.

**Comment by LukeTowers** [comment]
@geez0x1 Composer is the easiest way. I believe @aspendigital have a docker image that would pull in the latest develop branch, but I think it's having problems with the Composer 2.0 update at the moment.
